[build-system]
requires = ["uv_build>=0.8,<0.20"]
build-backend = "uv_build"

[project]
name = "ugdatalab"
version = "0.1.0"
dependencies = [
    "astropy",
    "astroquery",
    "corner",
    "joblib",
    "matplotlib",
    "numpy",
    "pandas",
    "pillow",
    "pymc",
    "requests",
    "scipy",
    "torch",
    "torchvision",
    "tqdm",
]

[project.optional-dependencies]
dev = ["pytest"]
labs = ["arviz", "dustmaps", "scikit-learn"]

[tool.uv.build-backend]
module-name = "ugdatalab"
module-root = ""

[dependency-groups]
dev = [
    "debugpy>=1.8.20",
    "ipykernel>=7.2.0",
]
